######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 19 10:11:52 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
